//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_peti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetivosEstrategicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObjetivosEstrategicos()
        {
            this.ObjetivosEspecificos = new HashSet<ObjetivosEspecificos>();
        }
    
        public int Id { get; set; }
        public int PlanId { get; set; }
        public string Objetivo { get; set; }
        public int Prioridad { get; set; }
        public Nullable<System.DateTime> FechaEstimada { get; set; }
        public bool Completado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjetivosEspecificos> ObjetivosEspecificos { get; set; }
        public virtual PlanEstrategico PlanEstrategico { get; set; }
    }
}
