//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_peti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjetivosEspecificos
    {
        public int Id { get; set; }
        public int ObjetivoId { get; set; }
        public string Detalle { get; set; }
        public bool Completado { get; set; }
        public Nullable<System.DateTime> FechaCompletado { get; set; }
        public Nullable<System.DateTime> FechaEstimada { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual ObjetivosEstrategicos ObjetivosEstrategicos { get; set; }
    }
}
